# Generated by Django 5.1.4 on 2026-07-20 14:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('municipalities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('certificate', 'Certificate'), ('payment', 'Tax / Utility Payment'), ('complaint', 'Complaint / Grievance'), ('license', 'License & Permit'), ('booking', 'Public Facility Booking'), ('rti', 'RTI Request'), ('scheme', 'Government Scheme'), ('emergency', 'Emergency Service')], max_length=20)),
                ('description', models.TextField()),
                ('eligibility', models.TextField(blank=True)),
                ('required_documents', models.JSONField(default=list)),
                ('processing_time_days', models.PositiveIntegerField(default=7)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fee_description', models.CharField(blank=True, max_length=255)),
                ('sla_hours', models.PositiveIntegerField(default=72, help_text='Service Level Agreement in hours')),
                ('is_online', models.BooleanField(default=True, help_text='Can be applied online?')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='municipalities.department')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='municipalities.municipality')),
            ],
            options={
                'db_table': 'services',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='services.service')),
            ],
            options={
                'db_table': 'service_faqs',
                'ordering': ['order'],
            },
        ),
    ]
