# Generated by Django 5.1.4 on 2026-07-20 14:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('municipalities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RTIAppeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appeal_number', models.CharField(max_length=50, unique=True)),
                ('appeal_type', models.CharField(choices=[('first_appeal', 'First Appeal'), ('second_appeal', 'Second Appeal')], max_length=20)),
                ('grounds_for_appeal', models.TextField(help_text='Reasons for filing the appeal')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='submitted', max_length=20)),
                ('appeal_response', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response_due_date', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_rti_appeals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rti_appeals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RTIRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rti_number', models.CharField(max_length=50, unique=True)),
                ('subject', models.CharField(max_length=500)),
                ('information_sought', models.TextField(help_text='Details of information being requested')),
                ('authority_type', models.CharField(choices=[('central', 'Central Government'), ('state', 'State Government'), ('municipal', 'Municipal Corporation')], default='municipal', max_length=20)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('information_provided', 'Information Provided'), ('rejected', 'Rejected'), ('first_appeal', 'First Appeal'), ('second_appeal', 'Second Appeal'), ('closed', 'Closed')], default='submitted', max_length=20)),
                ('fees_paid', models.DecimalField(decimal_places=2, default=10.0, max_digits=8)),
                ('fees_exemption_reason', models.TextField(blank=True)),
                ('response_text', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('response_due_date', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_rti_requests', to=settings.AUTH_USER_MODEL)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rti_requests', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rti_requests', to='municipalities.department')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rti_requests', to='municipalities.municipality')),
            ],
            options={
                'db_table': 'rti_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RTIDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.FileField(upload_to='rti/documents/')),
                ('document_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('request', 'Request Document'), ('response', 'Response Document'), ('appeal', 'Appeal Document'), ('supporting', 'Supporting Document')], default='request', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('rti_appeal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='rti.rtiappeal')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rti_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='rti.rtirequest')),
            ],
            options={
                'db_table': 'rti_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='rtiappeal',
            name='original_rti',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='rti.rtirequest'),
        ),
        migrations.CreateModel(
            name='RTITimeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('actor_role', models.CharField(blank=True, help_text='Citizen, Officer, Admin', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rti_appeal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='rti.rtiappeal')),
                ('rti_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='rti.rtirequest')),
            ],
            options={
                'db_table': 'rti_timeline',
                'ordering': ['-timestamp'],
            },
        ),
    ]
