/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as VoiceAssistantRouteImport } from "./routes/voice-assistant";
import { Route as TrackRouteImport } from "./routes/track";
import { Route as SettingsRouteImport } from "./routes/settings";
import { Route as ServicesRouteImport } from "./routes/services";
import { Route as SchemesRouteImport } from "./routes/schemes";
import { Route as RtiRouteImport } from "./routes/rti";
import { Route as RightsRouteImport } from "./routes/rights";
import { Route as ResourcesRouteImport } from "./routes/resources";
import { Route as PropertiesRouteImport } from "./routes/properties";
import { Route as ProfileRouteImport } from "./routes/profile";
import { Route as PaymentsRouteImport } from "./routes/payments";
import { Route as NotificationsRouteImport } from "./routes/notifications";
import { Route as MapsRouteImport } from "./routes/maps";
import { Route as LicensesRouteImport } from "./routes/licenses";
import { Route as HelpCenterRouteImport } from "./routes/help-center";
import { Route as FamilyRouteImport } from "./routes/family";
import { Route as DocumentsRouteImport } from "./routes/documents";
import { Route as DashboardRouteImport } from "./routes/dashboard";
import { Route as ComplaintsRouteImport } from "./routes/complaints";
import { Route as CertificatesRouteImport } from "./routes/certificates";
import { Route as BookingsRouteImport } from "./routes/bookings";
import { Route as AuthRouteImport } from "./routes/auth";
import { Route as ApplicationsRouteImport } from "./routes/applications";
import { Route as AiAssistantRouteImport } from "./routes/ai-assistant";
import { Route as AdminRouteImport } from "./routes/admin";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AiIndexRouteImport } from "./routes/ai.index";
import { Route as PaymentsHistoryRouteImport } from "./routes/payments.history";
import { Route as OfficerWorkflowsRouteImport } from "./routes/officer.workflows";
import { Route as OfficerTasksRouteImport } from "./routes/officer.tasks";
import { Route as OfficerReportsRouteImport } from "./routes/officer.reports";
import { Route as OfficerInspectionsRouteImport } from "./routes/officer.inspections";
import { Route as OfficerDashboardRouteImport } from "./routes/officer.dashboard";
import { Route as OfficerComplaintsRouteImport } from "./routes/officer.complaints";
import { Route as AiBotRouteImport } from "./routes/ai.$bot";
import { Route as AdminWorkflowsRouteImport } from "./routes/admin.workflows";
import { Route as AdminUsersRouteImport } from "./routes/admin.users";
import { Route as AdminSettingsRouteImport } from "./routes/admin.settings";
import { Route as AdminServicesRouteImport } from "./routes/admin.services";
import { Route as AdminRolesRouteImport } from "./routes/admin.roles";
import { Route as AdminDepartmentsRouteImport } from "./routes/admin.departments";
import { Route as AdminCmsRouteImport } from "./routes/admin.cms";
import { Route as AdminAnalyticsRouteImport } from "./routes/admin.analytics";

const VoiceAssistantRoute = VoiceAssistantRouteImport.update({
  id: "/voice-assistant",
  path: "/voice-assistant",
  getParentRoute: () => rootRouteImport,
} as any);
const TrackRoute = TrackRouteImport.update({
  id: "/track",
  path: "/track",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const ServicesRoute = ServicesRouteImport.update({
  id: "/services",
  path: "/services",
  getParentRoute: () => rootRouteImport,
} as any);
const SchemesRoute = SchemesRouteImport.update({
  id: "/schemes",
  path: "/schemes",
  getParentRoute: () => rootRouteImport,
} as any);
const RtiRoute = RtiRouteImport.update({
  id: "/rti",
  path: "/rti",
  getParentRoute: () => rootRouteImport,
} as any);
const RightsRoute = RightsRouteImport.update({
  id: "/rights",
  path: "/rights",
  getParentRoute: () => rootRouteImport,
} as any);
const ResourcesRoute = ResourcesRouteImport.update({
  id: "/resources",
  path: "/resources",
  getParentRoute: () => rootRouteImport,
} as any);
const PropertiesRoute = PropertiesRouteImport.update({
  id: "/properties",
  path: "/properties",
  getParentRoute: () => rootRouteImport,
} as any);
const ProfileRoute = ProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => rootRouteImport,
} as any);
const PaymentsRoute = PaymentsRouteImport.update({
  id: "/payments",
  path: "/payments",
  getParentRoute: () => rootRouteImport,
} as any);
const NotificationsRoute = NotificationsRouteImport.update({
  id: "/notifications",
  path: "/notifications",
  getParentRoute: () => rootRouteImport,
} as any);
const MapsRoute = MapsRouteImport.update({
  id: "/maps",
  path: "/maps",
  getParentRoute: () => rootRouteImport,
} as any);
const LicensesRoute = LicensesRouteImport.update({
  id: "/licenses",
  path: "/licenses",
  getParentRoute: () => rootRouteImport,
} as any);
const HelpCenterRoute = HelpCenterRouteImport.update({
  id: "/help-center",
  path: "/help-center",
  getParentRoute: () => rootRouteImport,
} as any);
const FamilyRoute = FamilyRouteImport.update({
  id: "/family",
  path: "/family",
  getParentRoute: () => rootRouteImport,
} as any);
const DocumentsRoute = DocumentsRouteImport.update({
  id: "/documents",
  path: "/documents",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const ComplaintsRoute = ComplaintsRouteImport.update({
  id: "/complaints",
  path: "/complaints",
  getParentRoute: () => rootRouteImport,
} as any);
const CertificatesRoute = CertificatesRouteImport.update({
  id: "/certificates",
  path: "/certificates",
  getParentRoute: () => rootRouteImport,
} as any);
const BookingsRoute = BookingsRouteImport.update({
  id: "/bookings",
  path: "/bookings",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRoute = AuthRouteImport.update({
  id: "/auth",
  path: "/auth",
  getParentRoute: () => rootRouteImport,
} as any);
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: "/applications",
  path: "/applications",
  getParentRoute: () => rootRouteImport,
} as any);
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: "/ai-assistant",
  path: "/ai-assistant",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminRoute = AdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AiIndexRoute = AiIndexRouteImport.update({
  id: "/ai/",
  path: "/ai/",
  getParentRoute: () => rootRouteImport,
} as any);
const PaymentsHistoryRoute = PaymentsHistoryRouteImport.update({
  id: "/history",
  path: "/history",
  getParentRoute: () => PaymentsRoute,
} as any);
const OfficerWorkflowsRoute = OfficerWorkflowsRouteImport.update({
  id: "/officer/workflows",
  path: "/officer/workflows",
  getParentRoute: () => rootRouteImport,
} as any);
const OfficerTasksRoute = OfficerTasksRouteImport.update({
  id: "/officer/tasks",
  path: "/officer/tasks",
  getParentRoute: () => rootRouteImport,
} as any);
const OfficerReportsRoute = OfficerReportsRouteImport.update({
  id: "/officer/reports",
  path: "/officer/reports",
  getParentRoute: () => rootRouteImport,
} as any);
const OfficerInspectionsRoute = OfficerInspectionsRouteImport.update({
  id: "/officer/inspections",
  path: "/officer/inspections",
  getParentRoute: () => rootRouteImport,
} as any);
const OfficerDashboardRoute = OfficerDashboardRouteImport.update({
  id: "/officer/dashboard",
  path: "/officer/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const OfficerComplaintsRoute = OfficerComplaintsRouteImport.update({
  id: "/officer/complaints",
  path: "/officer/complaints",
  getParentRoute: () => rootRouteImport,
} as any);
const AiBotRoute = AiBotRouteImport.update({
  id: "/ai/$bot",
  path: "/ai/$bot",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminWorkflowsRoute = AdminWorkflowsRouteImport.update({
  id: "/workflows",
  path: "/workflows",
  getParentRoute: () => AdminRoute,
} as any);
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: "/users",
  path: "/users",
  getParentRoute: () => AdminRoute,
} as any);
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => AdminRoute,
} as any);
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: "/services",
  path: "/services",
  getParentRoute: () => AdminRoute,
} as any);
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: "/roles",
  path: "/roles",
  getParentRoute: () => AdminRoute,
} as any);
const AdminDepartmentsRoute = AdminDepartmentsRouteImport.update({
  id: "/departments",
  path: "/departments",
  getParentRoute: () => AdminRoute,
} as any);
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: "/cms",
  path: "/cms",
  getParentRoute: () => AdminRoute,
} as any);
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: "/analytics",
  path: "/analytics",
  getParentRoute: () => AdminRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/admin": typeof AdminRouteWithChildren;
  "/ai-assistant": typeof AiAssistantRoute;
  "/applications": typeof ApplicationsRoute;
  "/auth": typeof AuthRoute;
  "/bookings": typeof BookingsRoute;
  "/certificates": typeof CertificatesRoute;
  "/complaints": typeof ComplaintsRoute;
  "/dashboard": typeof DashboardRoute;
  "/documents": typeof DocumentsRoute;
  "/family": typeof FamilyRoute;
  "/help-center": typeof HelpCenterRoute;
  "/licenses": typeof LicensesRoute;
  "/maps": typeof MapsRoute;
  "/notifications": typeof NotificationsRoute;
  "/payments": typeof PaymentsRouteWithChildren;
  "/profile": typeof ProfileRoute;
  "/properties": typeof PropertiesRoute;
  "/resources": typeof ResourcesRoute;
  "/rights": typeof RightsRoute;
  "/rti": typeof RtiRoute;
  "/schemes": typeof SchemesRoute;
  "/services": typeof ServicesRoute;
  "/settings": typeof SettingsRoute;
  "/track": typeof TrackRoute;
  "/voice-assistant": typeof VoiceAssistantRoute;
  "/admin/analytics": typeof AdminAnalyticsRoute;
  "/admin/cms": typeof AdminCmsRoute;
  "/admin/departments": typeof AdminDepartmentsRoute;
  "/admin/roles": typeof AdminRolesRoute;
  "/admin/services": typeof AdminServicesRoute;
  "/admin/settings": typeof AdminSettingsRoute;
  "/admin/users": typeof AdminUsersRoute;
  "/admin/workflows": typeof AdminWorkflowsRoute;
  "/ai/$bot": typeof AiBotRoute;
  "/officer/complaints": typeof OfficerComplaintsRoute;
  "/officer/dashboard": typeof OfficerDashboardRoute;
  "/officer/inspections": typeof OfficerInspectionsRoute;
  "/officer/reports": typeof OfficerReportsRoute;
  "/officer/tasks": typeof OfficerTasksRoute;
  "/officer/workflows": typeof OfficerWorkflowsRoute;
  "/payments/history": typeof PaymentsHistoryRoute;
  "/ai/": typeof AiIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/admin": typeof AdminRouteWithChildren;
  "/ai-assistant": typeof AiAssistantRoute;
  "/applications": typeof ApplicationsRoute;
  "/auth": typeof AuthRoute;
  "/bookings": typeof BookingsRoute;
  "/certificates": typeof CertificatesRoute;
  "/complaints": typeof ComplaintsRoute;
  "/dashboard": typeof DashboardRoute;
  "/documents": typeof DocumentsRoute;
  "/family": typeof FamilyRoute;
  "/help-center": typeof HelpCenterRoute;
  "/licenses": typeof LicensesRoute;
  "/maps": typeof MapsRoute;
  "/notifications": typeof NotificationsRoute;
  "/payments": typeof PaymentsRouteWithChildren;
  "/profile": typeof ProfileRoute;
  "/properties": typeof PropertiesRoute;
  "/resources": typeof ResourcesRoute;
  "/rights": typeof RightsRoute;
  "/rti": typeof RtiRoute;
  "/schemes": typeof SchemesRoute;
  "/services": typeof ServicesRoute;
  "/settings": typeof SettingsRoute;
  "/track": typeof TrackRoute;
  "/voice-assistant": typeof VoiceAssistantRoute;
  "/admin/analytics": typeof AdminAnalyticsRoute;
  "/admin/cms": typeof AdminCmsRoute;
  "/admin/departments": typeof AdminDepartmentsRoute;
  "/admin/roles": typeof AdminRolesRoute;
  "/admin/services": typeof AdminServicesRoute;
  "/admin/settings": typeof AdminSettingsRoute;
  "/admin/users": typeof AdminUsersRoute;
  "/admin/workflows": typeof AdminWorkflowsRoute;
  "/ai/$bot": typeof AiBotRoute;
  "/officer/complaints": typeof OfficerComplaintsRoute;
  "/officer/dashboard": typeof OfficerDashboardRoute;
  "/officer/inspections": typeof OfficerInspectionsRoute;
  "/officer/reports": typeof OfficerReportsRoute;
  "/officer/tasks": typeof OfficerTasksRoute;
  "/officer/workflows": typeof OfficerWorkflowsRoute;
  "/payments/history": typeof PaymentsHistoryRoute;
  "/ai": typeof AiIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/admin": typeof AdminRouteWithChildren;
  "/ai-assistant": typeof AiAssistantRoute;
  "/applications": typeof ApplicationsRoute;
  "/auth": typeof AuthRoute;
  "/bookings": typeof BookingsRoute;
  "/certificates": typeof CertificatesRoute;
  "/complaints": typeof ComplaintsRoute;
  "/dashboard": typeof DashboardRoute;
  "/documents": typeof DocumentsRoute;
  "/family": typeof FamilyRoute;
  "/help-center": typeof HelpCenterRoute;
  "/licenses": typeof LicensesRoute;
  "/maps": typeof MapsRoute;
  "/notifications": typeof NotificationsRoute;
  "/payments": typeof PaymentsRouteWithChildren;
  "/profile": typeof ProfileRoute;
  "/properties": typeof PropertiesRoute;
  "/resources": typeof ResourcesRoute;
  "/rights": typeof RightsRoute;
  "/rti": typeof RtiRoute;
  "/schemes": typeof SchemesRoute;
  "/services": typeof ServicesRoute;
  "/settings": typeof SettingsRoute;
  "/track": typeof TrackRoute;
  "/voice-assistant": typeof VoiceAssistantRoute;
  "/admin/analytics": typeof AdminAnalyticsRoute;
  "/admin/cms": typeof AdminCmsRoute;
  "/admin/departments": typeof AdminDepartmentsRoute;
  "/admin/roles": typeof AdminRolesRoute;
  "/admin/services": typeof AdminServicesRoute;
  "/admin/settings": typeof AdminSettingsRoute;
  "/admin/users": typeof AdminUsersRoute;
  "/admin/workflows": typeof AdminWorkflowsRoute;
  "/ai/$bot": typeof AiBotRoute;
  "/officer/complaints": typeof OfficerComplaintsRoute;
  "/officer/dashboard": typeof OfficerDashboardRoute;
  "/officer/inspections": typeof OfficerInspectionsRoute;
  "/officer/reports": typeof OfficerReportsRoute;
  "/officer/tasks": typeof OfficerTasksRoute;
  "/officer/workflows": typeof OfficerWorkflowsRoute;
  "/payments/history": typeof PaymentsHistoryRoute;
  "/ai/": typeof AiIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/admin"
    | "/ai-assistant"
    | "/applications"
    | "/auth"
    | "/bookings"
    | "/certificates"
    | "/complaints"
    | "/dashboard"
    | "/documents"
    | "/family"
    | "/help-center"
    | "/licenses"
    | "/maps"
    | "/notifications"
    | "/payments"
    | "/profile"
    | "/properties"
    | "/resources"
    | "/rights"
    | "/rti"
    | "/schemes"
    | "/services"
    | "/settings"
    | "/track"
    | "/voice-assistant"
    | "/admin/analytics"
    | "/admin/cms"
    | "/admin/departments"
    | "/admin/roles"
    | "/admin/services"
    | "/admin/settings"
    | "/admin/users"
    | "/admin/workflows"
    | "/ai/$bot"
    | "/officer/complaints"
    | "/officer/dashboard"
    | "/officer/inspections"
    | "/officer/reports"
    | "/officer/tasks"
    | "/officer/workflows"
    | "/payments/history"
    | "/ai/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/admin"
    | "/ai-assistant"
    | "/applications"
    | "/auth"
    | "/bookings"
    | "/certificates"
    | "/complaints"
    | "/dashboard"
    | "/documents"
    | "/family"
    | "/help-center"
    | "/licenses"
    | "/maps"
    | "/notifications"
    | "/payments"
    | "/profile"
    | "/properties"
    | "/resources"
    | "/rights"
    | "/rti"
    | "/schemes"
    | "/services"
    | "/settings"
    | "/track"
    | "/voice-assistant"
    | "/admin/analytics"
    | "/admin/cms"
    | "/admin/departments"
    | "/admin/roles"
    | "/admin/services"
    | "/admin/settings"
    | "/admin/users"
    | "/admin/workflows"
    | "/ai/$bot"
    | "/officer/complaints"
    | "/officer/dashboard"
    | "/officer/inspections"
    | "/officer/reports"
    | "/officer/tasks"
    | "/officer/workflows"
    | "/payments/history"
    | "/ai";
  id:
    | "__root__"
    | "/"
    | "/admin"
    | "/ai-assistant"
    | "/applications"
    | "/auth"
    | "/bookings"
    | "/certificates"
    | "/complaints"
    | "/dashboard"
    | "/documents"
    | "/family"
    | "/help-center"
    | "/licenses"
    | "/maps"
    | "/notifications"
    | "/payments"
    | "/profile"
    | "/properties"
    | "/resources"
    | "/rights"
    | "/rti"
    | "/schemes"
    | "/services"
    | "/settings"
    | "/track"
    | "/voice-assistant"
    | "/admin/analytics"
    | "/admin/cms"
    | "/admin/departments"
    | "/admin/roles"
    | "/admin/services"
    | "/admin/settings"
    | "/admin/users"
    | "/admin/workflows"
    | "/ai/$bot"
    | "/officer/complaints"
    | "/officer/dashboard"
    | "/officer/inspections"
    | "/officer/reports"
    | "/officer/tasks"
    | "/officer/workflows"
    | "/payments/history"
    | "/ai/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AdminRoute: typeof AdminRouteWithChildren;
  AiAssistantRoute: typeof AiAssistantRoute;
  ApplicationsRoute: typeof ApplicationsRoute;
  AuthRoute: typeof AuthRoute;
  BookingsRoute: typeof BookingsRoute;
  CertificatesRoute: typeof CertificatesRoute;
  ComplaintsRoute: typeof ComplaintsRoute;
  DashboardRoute: typeof DashboardRoute;
  DocumentsRoute: typeof DocumentsRoute;
  FamilyRoute: typeof FamilyRoute;
  HelpCenterRoute: typeof HelpCenterRoute;
  LicensesRoute: typeof LicensesRoute;
  MapsRoute: typeof MapsRoute;
  NotificationsRoute: typeof NotificationsRoute;
  PaymentsRoute: typeof PaymentsRouteWithChildren;
  ProfileRoute: typeof ProfileRoute;
  PropertiesRoute: typeof PropertiesRoute;
  ResourcesRoute: typeof ResourcesRoute;
  RightsRoute: typeof RightsRoute;
  RtiRoute: typeof RtiRoute;
  SchemesRoute: typeof SchemesRoute;
  ServicesRoute: typeof ServicesRoute;
  SettingsRoute: typeof SettingsRoute;
  TrackRoute: typeof TrackRoute;
  VoiceAssistantRoute: typeof VoiceAssistantRoute;
  AiBotRoute: typeof AiBotRoute;
  OfficerComplaintsRoute: typeof OfficerComplaintsRoute;
  OfficerDashboardRoute: typeof OfficerDashboardRoute;
  OfficerInspectionsRoute: typeof OfficerInspectionsRoute;
  OfficerReportsRoute: typeof OfficerReportsRoute;
  OfficerTasksRoute: typeof OfficerTasksRoute;
  OfficerWorkflowsRoute: typeof OfficerWorkflowsRoute;
  AiIndexRoute: typeof AiIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/voice-assistant": {
      id: "/voice-assistant";
      path: "/voice-assistant";
      fullPath: "/voice-assistant";
      preLoaderRoute: typeof VoiceAssistantRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/track": {
      id: "/track";
      path: "/track";
      fullPath: "/track";
      preLoaderRoute: typeof TrackRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/services": {
      id: "/services";
      path: "/services";
      fullPath: "/services";
      preLoaderRoute: typeof ServicesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/schemes": {
      id: "/schemes";
      path: "/schemes";
      fullPath: "/schemes";
      preLoaderRoute: typeof SchemesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/rti": {
      id: "/rti";
      path: "/rti";
      fullPath: "/rti";
      preLoaderRoute: typeof RtiRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/rights": {
      id: "/rights";
      path: "/rights";
      fullPath: "/rights";
      preLoaderRoute: typeof RightsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/resources": {
      id: "/resources";
      path: "/resources";
      fullPath: "/resources";
      preLoaderRoute: typeof ResourcesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/properties": {
      id: "/properties";
      path: "/properties";
      fullPath: "/properties";
      preLoaderRoute: typeof PropertiesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/profile": {
      id: "/profile";
      path: "/profile";
      fullPath: "/profile";
      preLoaderRoute: typeof ProfileRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/payments": {
      id: "/payments";
      path: "/payments";
      fullPath: "/payments";
      preLoaderRoute: typeof PaymentsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/notifications": {
      id: "/notifications";
      path: "/notifications";
      fullPath: "/notifications";
      preLoaderRoute: typeof NotificationsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/maps": {
      id: "/maps";
      path: "/maps";
      fullPath: "/maps";
      preLoaderRoute: typeof MapsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/licenses": {
      id: "/licenses";
      path: "/licenses";
      fullPath: "/licenses";
      preLoaderRoute: typeof LicensesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/help-center": {
      id: "/help-center";
      path: "/help-center";
      fullPath: "/help-center";
      preLoaderRoute: typeof HelpCenterRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/family": {
      id: "/family";
      path: "/family";
      fullPath: "/family";
      preLoaderRoute: typeof FamilyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/documents": {
      id: "/documents";
      path: "/documents";
      fullPath: "/documents";
      preLoaderRoute: typeof DocumentsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/complaints": {
      id: "/complaints";
      path: "/complaints";
      fullPath: "/complaints";
      preLoaderRoute: typeof ComplaintsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/certificates": {
      id: "/certificates";
      path: "/certificates";
      fullPath: "/certificates";
      preLoaderRoute: typeof CertificatesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/bookings": {
      id: "/bookings";
      path: "/bookings";
      fullPath: "/bookings";
      preLoaderRoute: typeof BookingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth": {
      id: "/auth";
      path: "/auth";
      fullPath: "/auth";
      preLoaderRoute: typeof AuthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/applications": {
      id: "/applications";
      path: "/applications";
      fullPath: "/applications";
      preLoaderRoute: typeof ApplicationsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/ai-assistant": {
      id: "/ai-assistant";
      path: "/ai-assistant";
      fullPath: "/ai-assistant";
      preLoaderRoute: typeof AiAssistantRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin": {
      id: "/admin";
      path: "/admin";
      fullPath: "/admin";
      preLoaderRoute: typeof AdminRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/ai/": {
      id: "/ai/";
      path: "/ai";
      fullPath: "/ai/";
      preLoaderRoute: typeof AiIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/payments/history": {
      id: "/payments/history";
      path: "/history";
      fullPath: "/payments/history";
      preLoaderRoute: typeof PaymentsHistoryRouteImport;
      parentRoute: typeof PaymentsRoute;
    };
    "/officer/workflows": {
      id: "/officer/workflows";
      path: "/officer/workflows";
      fullPath: "/officer/workflows";
      preLoaderRoute: typeof OfficerWorkflowsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/officer/tasks": {
      id: "/officer/tasks";
      path: "/officer/tasks";
      fullPath: "/officer/tasks";
      preLoaderRoute: typeof OfficerTasksRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/officer/reports": {
      id: "/officer/reports";
      path: "/officer/reports";
      fullPath: "/officer/reports";
      preLoaderRoute: typeof OfficerReportsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/officer/inspections": {
      id: "/officer/inspections";
      path: "/officer/inspections";
      fullPath: "/officer/inspections";
      preLoaderRoute: typeof OfficerInspectionsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/officer/dashboard": {
      id: "/officer/dashboard";
      path: "/officer/dashboard";
      fullPath: "/officer/dashboard";
      preLoaderRoute: typeof OfficerDashboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/officer/complaints": {
      id: "/officer/complaints";
      path: "/officer/complaints";
      fullPath: "/officer/complaints";
      preLoaderRoute: typeof OfficerComplaintsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/ai/$bot": {
      id: "/ai/$bot";
      path: "/ai/$bot";
      fullPath: "/ai/$bot";
      preLoaderRoute: typeof AiBotRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin/workflows": {
      id: "/admin/workflows";
      path: "/workflows";
      fullPath: "/admin/workflows";
      preLoaderRoute: typeof AdminWorkflowsRouteImport;
      parentRoute: typeof AdminRoute;
    };
    "/admin/users": {
      id: "/admin/users";
      path: "/users";
      fullPath: "/admin/users";
      preLoaderRoute: typeof AdminUsersRouteImport;
      parentRoute: typeof AdminRoute;
    };
    "/admin/settings": {
      id: "/admin/settings";
      path: "/settings";
      fullPath: "/admin/settings";
      preLoaderRoute: typeof AdminSettingsRouteImport;
      parentRoute: typeof AdminRoute;
    };
    "/admin/services": {
      id: "/admin/services";
      path: "/services";
      fullPath: "/admin/services";
      preLoaderRoute: typeof AdminServicesRouteImport;
      parentRoute: typeof AdminRoute;
    };
    "/admin/roles": {
      id: "/admin/roles";
      path: "/roles";
      fullPath: "/admin/roles";
      preLoaderRoute: typeof AdminRolesRouteImport;
      parentRoute: typeof AdminRoute;
    };
    "/admin/departments": {
      id: "/admin/departments";
      path: "/departments";
      fullPath: "/admin/departments";
      preLoaderRoute: typeof AdminDepartmentsRouteImport;
      parentRoute: typeof AdminRoute;
    };
    "/admin/cms": {
      id: "/admin/cms";
      path: "/cms";
      fullPath: "/admin/cms";
      preLoaderRoute: typeof AdminCmsRouteImport;
      parentRoute: typeof AdminRoute;
    };
    "/admin/analytics": {
      id: "/admin/analytics";
      path: "/analytics";
      fullPath: "/admin/analytics";
      preLoaderRoute: typeof AdminAnalyticsRouteImport;
      parentRoute: typeof AdminRoute;
    };
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute;
  AdminCmsRoute: typeof AdminCmsRoute;
  AdminDepartmentsRoute: typeof AdminDepartmentsRoute;
  AdminRolesRoute: typeof AdminRolesRoute;
  AdminServicesRoute: typeof AdminServicesRoute;
  AdminSettingsRoute: typeof AdminSettingsRoute;
  AdminUsersRoute: typeof AdminUsersRoute;
  AdminWorkflowsRoute: typeof AdminWorkflowsRoute;
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCmsRoute: AdminCmsRoute,
  AdminDepartmentsRoute: AdminDepartmentsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWorkflowsRoute: AdminWorkflowsRoute,
};

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren);

interface PaymentsRouteChildren {
  PaymentsHistoryRoute: typeof PaymentsHistoryRoute;
}

const PaymentsRouteChildren: PaymentsRouteChildren = {
  PaymentsHistoryRoute: PaymentsHistoryRoute,
};

const PaymentsRouteWithChildren = PaymentsRoute._addFileChildren(
  PaymentsRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AiAssistantRoute: AiAssistantRoute,
  ApplicationsRoute: ApplicationsRoute,
  AuthRoute: AuthRoute,
  BookingsRoute: BookingsRoute,
  CertificatesRoute: CertificatesRoute,
  ComplaintsRoute: ComplaintsRoute,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRoute,
  FamilyRoute: FamilyRoute,
  HelpCenterRoute: HelpCenterRoute,
  LicensesRoute: LicensesRoute,
  MapsRoute: MapsRoute,
  NotificationsRoute: NotificationsRoute,
  PaymentsRoute: PaymentsRouteWithChildren,
  ProfileRoute: ProfileRoute,
  PropertiesRoute: PropertiesRoute,
  ResourcesRoute: ResourcesRoute,
  RightsRoute: RightsRoute,
  RtiRoute: RtiRoute,
  SchemesRoute: SchemesRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
  TrackRoute: TrackRoute,
  VoiceAssistantRoute: VoiceAssistantRoute,
  AiBotRoute: AiBotRoute,
  OfficerComplaintsRoute: OfficerComplaintsRoute,
  OfficerDashboardRoute: OfficerDashboardRoute,
  OfficerInspectionsRoute: OfficerInspectionsRoute,
  OfficerReportsRoute: OfficerReportsRoute,
  OfficerTasksRoute: OfficerTasksRoute,
  OfficerWorkflowsRoute: OfficerWorkflowsRoute,
  AiIndexRoute: AiIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
