# Generated by Django 5.1.4 on 2026-07-20 14:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('municipalities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('payment_type', models.CharField(choices=[('property_tax', 'Property Tax'), ('water_bill', 'Water Bill'), ('drainage', 'Drainage Bill'), ('professional_tax', 'Professional Tax'), ('trade_license', 'Trade License Fee'), ('miscellaneous', 'Miscellaneous')], max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('mode', models.CharField(choices=[('upi', 'UPI'), ('net_banking', 'Net Banking'), ('card', 'Debit / Credit Card'), ('cash', 'Cash'), ('cheque', 'Cheque')], default='upi', max_length=20)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('property_id', models.CharField(blank=True, help_text='Property ID for property tax', max_length=100)),
                ('consumer_number', models.CharField(blank=True, help_text='Water/electricity consumer number', max_length=100)),
                ('period', models.CharField(blank=True, help_text='Billing period e.g. Q1 2024-25', max_length=50)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='municipalities.municipality')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
